/*
 * File: app/controller/TunesController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TunesMini.controller.TunesController', {
    extend: 'Ext.app.Controller',

    onTunesViewItemDblClick: function(dataview, record, item, index, e, eOpts) {
        // Create an instance of the preview window
        // Have it update its template with the record the user selected
        // Show it

        Ext.create('TunesMini.view.PreviewWindow', {
            data: record.getData(),
            title: record.get('title')  + ', provided courtesy of iTunes'
        });

    },

    init: function(application) {
        this.control({
            "#tunesView": {
                itemdblclick: this.onTunesViewItemDblClick
            }
        });
    }

});
