/*
 * File: app/view/Umbrella.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Umbrella.view.Umbrella', {
    extend: 'Ext.Container',
    alias: 'widget.umbrella',

    requires: [
        'Ext.Img',
        'Ext.TitleBar'
    ],

    config: {
        layout: 'card',
        rainy: null,
        items: [
            {
                xtype: 'container',
                masked: {
                    xtype: 'loadmask',
                    message: 'Checking for rain...'
                }
            },
            {
                xtype: 'image',
                itemId: 'closed',
                src: 'resources/images/ClosedUmbrella.jpg'
            },
            {
                xtype: 'image',
                itemId: 'open',
                src: 'resources/images/OpenUmbrella.jpg'
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                itemId: 'title'
            }
        ]
    },

    updateRainy: function(rainy) {
        if (rainy){
            this.setActiveItem('#open');
            this.down('#title').setTitle('Take Your Umbrella');
        } else {
            this.setActiveItem('#closed');
            this.down('#title').setTitle('Leave Your Umbrella');
        }
    }

});