/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TunesMini.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'iTunes Music Videos',
                    items: [
                        {
                            xtype: 'dataview',
                            itemId: 'tunesView',
                            autoScroll: true,
                            itemCls: 'video',
                            itemSelector: 'div',
                            itemTpl: [
                                '<a href="{link}" target="itunes_store">',
                                '    <img src="resources/images/iTunesBadge.gif"/>',
                                '</a>',
                                '<figure>',
                                '    <img src="{image}" />',
                                '    <figcaption>{title}<br/>{artist}</figcaption><br/>',
                                '</figure>',
                                ''
                            ],
                            overItemCls: 'overvideo',
                            store: 'Tunes'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});