/*
 * File: app/view/PreviewWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TunesMini.view.PreviewWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.XTemplate'
    ],

    autoShow: true,
    height: 352,
    width: 640,
    resizable: false,
    title: 'My Window',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: [
                '<video autoplay preload="auto"><source src="{preview}" type="video/mp4"></video>'
            ]
        });

        me.callParent(arguments);
    }

});